AWSTemplateFormatVersion: 2010-09-09

## =================== DESCRIPTION =================== ##
Description: >-
  AWS CloudFormation sample template
  - Create a new S3 bucket and it's policy, configure it to host a static website  

## =================== PARAMETERS =================== ##
Parameters:
  paramStaticWebsiteHostingBucketName:
    Description: Specify an existing S3 bucket that hosts static website
    Type: String
    Default: westworld-website-hosting-bucket

## =================== RESOURCES =================== ##
Resources:
# ...
  myCloudFrontOriginAccessIdentity: # kali - find out
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref paramStaticWebsiteHostingBucketName # kali - find out

  # ....
  myCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt 'paramStaticWebsiteHostingBucketName.DomainName' # kali - incorrect, fix it
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${myCloudFrontOriginAccessIdentity}'
        CustomErrorResponses: # kali - move to the end
          - ErrorCode: 403 # not found
            ResponseCode: 404
            ResponsePagePath: '/error.html' # kali - add error.html to the frontend
            ErrorCachingMinTTL: 60 # kali - find out do you need it
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600 # 1 hour
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400 # 24 hours
          MinTTL: 60 # 1 min
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: 'allow-all'
        # This DefaultRootObject configuration is not enough.
        DefaultRootObject: '/index.html'
        Enabled: true
        HttpVersion: http2
        PriceClass: 'PriceClass_All'

  # Create an IAM user with Access Keys to enable automated deployment of the website to this bucket
  PublishUser:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: !Sub 'publish-to-${S3Bucket}'
          PolicyDocument:
            Statement:
              - Action: 's3:*'
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:s3:::${S3Bucket}'
                  - !Sub 'arn:aws:s3:::${S3Bucket}/*'

  PublishCredentials:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref PublishUser

## =================== OUTPUT =================== ##
Outputs:  





  # kali 
  myRoute53RecordSetGroup:
        Type: 'AWS::Route53::RecordSetGroup'
        Properties:
          HostedZoneName: !Sub "${paramRootDomain}." # keep the . suffix, e.g. 'example.com.'
          RecordSets:
            - Name: !Ref DomainName
              Type: A # A routes traffic to an IPv4 address and some AWS resources
              AliasTarget:
                  DNSName: S3 ... 
                  HostedZoneId: !Ref paramHostedZoneId # for S3 bucket use the hosted zone ID for the region that you created the bucket in
                  EvaluateTargetHealth: false
            - Name: !Sub ${paramSubdomain}.${paramRootDomain}
              Type: A # A routes traffic to an IPv4 address and some AWS resources
              AliasTarget:
                  DNSName: !GetAtt CloudFrontDistribution.DomainName
                  EvaluateTargetHealth: false
                  HostedZoneId: !Ref paramHostedZoneId # for S3 bucket use the hosted zone ID for the region that you created the bucket in


URL:
    Description: 'URL to static website.'
    Value: !Sub 'https://${DomainName}'


  paramCertificateType:
    Description: Specify which certificate to use - either from AWS Certificate Manager or AWS IAM. CreateAcmCertificate only works in the us-east-1 region.
    Type: String
    Default: IamCertificateId
    AllowedValues:
    - AcmCertificateArn
    - IamCertificateId
    - CreateAcmCertificate    