name: iac-scan-ci
on:
 workflow_dispatch: {}
jobs:
 iac-ci-scan-kicks:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v3
   - name: kicks analysis
     uses: checkmarx/kics-github-action@v2.1.0
     with:
          path: 'cloudformation/module3'
          profiling: MEM
          output_path: myResults/
 iac-ci-scan-checkov:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v3
   - name: Test with Checkov
     id: checkov
     uses: bridgecrewio/checkov-action@master
     with:
       directory: cloudformation/module3
       framework: cloudformation
  
